### ISSUE TITLE
Create and test addObservationPeriod

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/CohortProfiles#37]
Create the function:
addObservationPeriod<- function(x, column = c("observation_period_start_date", "observation_period_end_date"), name = column)

add one or two columns depending on the value of column.
Make sure there are no multipli observation periods

Add tests with following structure:
- First group of tests: check input length and type for each of the arguments
- Second gorup of tests: test that cdm$cohort1 %>% addObservationPeriod(cdm) and cdm$condition_occurrence %>% addObservationPeriod(cdm) work
- following tests: check that all parameters have the desired result.

Ensure 100% test coverage

Make sure that example and description of function and variables are populated

**Comment by ilovemane** [comment]
@catalamarti this might be a daft question, so what will the function does if there are multiple observation periods?

**Comment by catalamarti** [comment]
@ilovemane 
I would add then the observation period that the observation is in.
Name is the name of the columns, by default it is the name of the columns, but you can change manually if the user wants.

**Comment by ilovemane** [comment]
@catalamarti is this similar to add prior history but add a column for the obersvation_start_date and  for obersvation_end_date.
