### ISSUE TITLE
create addDemographics

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/CohortProfiles#39]
addDemographics <- function(x, cdm, demographicsAt = "cohort_start_date", ageGroup = NULL)

```
x <- x %>%
  addAge(cdm, ageAt = demographcsAt) %>%
  addSex(cdm) %>%
  addPriorHistory(cdm, priorHistoryAt = demographicsAt) 
if (!is.null(ageGroup)) {
  x <- x %>%
    addAgeGroups(cdm, ageGroup = ageGroup)
}
return(x)
```

**add tests, checks and documentation**

**Comment by KimLopezGuell** [comment]
There's a strange issue in this function that only appears when testing in github, but not in my PC. To be studied.
